FROM nginx:alpine

#WORKDIR /app

#ENV PATH /app/node_modules/.bin:$PATH
COPY /dist/spotify-study-break/* /usr/share/nginx/html/
EXPOSE 80
#COPY package.json /app
#RUN npm install
#RUN npm install -g @angular/cli@7.3.9

#COPY . /app

#EXPOSE 4200

#CMD ["npm", "start"]
#RUN ng serve